### ISSUE TITLE
grad calculation question

### ISSUE THREAD

**Issue by hnshahao** [teddykoker/blog#1]
hello, Thanks for your great work. I learned a lot from your posts

I have a question.

On post 

trading-with-reinforcement-learning-in-python-part-two-application.ipynb

each time step, the flowing grad is calculated
(dRdF * dFdtheta + dRdFp * dFpdtheta)

my question is: it seems this is only part of grad of each step?

**Comment by teddykoker** [comment]
Good catch! Fixed.
