### ISSUE TITLE
Momentum Equity Clenow List Sorting

### ISSUE THREAD

**Issue by neillbyrne** [teddykoker/blog#18]
Thanks for the bt version of Clenow momentum equity strategy. 

QQ: Should the rankings be reverse sorted, as we want higher values first?

The line

`self.rankings.sort(key=lambda d: self.inds[d]["momentum"][0])`

would become

`self.rankings.sort(key=lambda d: self.inds[d]["momentum"][0], reverse=True)`

**Comment by teddykoker** [comment]
Thanks for pointing this out! You are correct and I have fixed the code in the notebook and post. Unfortunately I am unable to run the results again; I do not have access to the same exact data.
