### ISSUE TITLE
gradient - dbdr

### ISSUE THREAD

**Issue by tasilva96** [teddykoker/blog#7]
Hi,

I am using [your code](https://github.com/teddykoker/blog/blob/master/_notebooks/2019-06-04-trading-with-reinforcement-learning-in-python-part-ii-application.ipynb) and I wonder if it should be `dBdR = 2. * R / T`.

Thank you.

**Comment by teddykoker** [comment]
That is the same thing mathematically.

**Comment by tasilva96** [comment]
True!

I noticed you mentioned that the trader function (F) will generate a value between 0 and 1 but, in reality, it will generate a value between -1 and 1. It allows for short sell.

**Comment by teddykoker** [comment]
Good catch! I had changed it but forgot to change the text.

**Comment by teddykoker** [comment]
Fixed :)
