### ISSUE TITLE
Momentum stock selection

### ISSUE THREAD

**Issue by Kerberos007** [teddykoker/blog#8]
best30 = momentums30.iloc[-1:].max().sort_values(ascending=False).index[:5]
plt.figure(figsize=(12, 9))
plt.xlabel('Days')
plt.ylabel('Stock Price')
for best in best30:
    print ("best = ", best, " momentum = ", momentums30[best].iloc[-1 :])
    rets = np.log(stocks[best].iloc[-30 :])
    x = np.arange(len(rets))
    slope, intercept, r_value, p_value, std_err = linregress(x, rets)
    plt.plot(np.arange(90), stocks[best][-90:]);
    y = np.arange(60, 90)
    z = np.e ** (intercept + slope*x)
    plt.plot(y, z)
    plt.show();

Hello, great work.  But, I just read thru here and found some trouble understanding this.  Don't you want to find the best 5 momentum stocks of the the current day, not anyday in the past?
hence, I changed the code to 
best30 = momentums30.iloc[-1:].max().sort_values(ascending=False).index[:5]
to get the current day best 5 momentum candidates. ( i used 30 days momentum in this example)

Also changed the plot on regression line from the current day back to 30 days ago.

a. I plotted the 90 day stock prices from 90 days ago to today
b. plotted the regression line only for the last 30 days of the stock prices.

I believe this makes much more sense.  

Comments? thanks in advance.

**Comment by teddykoker** [comment]
The plot I show in the post is simply showing an example of picks that the algorithm may choose; I thought it would be a good way to visualize how the momentum calculation works. Farther down in the strategy portion of the post, you can see that I rank the stocks based of the day's momentum value: 
```python
 self.rankings.sort(key=lambda d: self.inds[d]["momentum"][0])
```
If you wanted to visualize these picks you could certainly do something like the code listed above.

**Comment by Kerberos007** [comment]
Got it.  Thank you.
